name: update and buid rsshub docs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'

jobs:
  build_rsshub_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0 # Fetch all history
      
      - name: update rsshub docs
        run: |
          git submodule update --init --checkout rsshub
      
      - name: build docs
        run: |
          cp rsshub-package.json rsshub/package.json
          cd rsshub
          npm i && npm run docs:build
          cd ..
      
      - name: deploy docs
        run: |
          test -d docs/rsshub && rm -rf docs/rsshub
          cp -r rsshub/docs/.vuepress/dist docs/rsshub
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "rsshub docs updated by GitHub Actions"
          git push
