name: update rsshub docs

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0 # Fetch all history
        run: |
          git submodule update --init --checkout rsshub
          git config user.name SylleoYr
          git config user.email SylleoYr@users.noreply.github.com
          git add .
          git commit -m "update rsshub docs by GitHub Actions"
          git push
